# Generated by Django 3.1.2 on 2020-10-27 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField()),
                ('desc', models.CharField(choices=[('daily', 'd'), ('weekly', 'w'), ('biweekly', 'b'), ('monthly', 'm'), ('quarterly', 'q')], default='daily', max_length=20)),
            ],
        ),
    ]
