# Generated by Django 3.1.2 on 2020-10-27 01:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasker', '0002_auto_20201026_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 26, 20, 34, 44, 458504)),
        ),
    ]
