# Generated by Django 3.1.2 on 2020-11-21 14:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('color', models.CharField(choices=[('blue', 'Blue'), ('black', 'Black'), ('white', 'White'), ('yellow', 'Yellow'), ('orange', 'Orange'), ('pink', 'Pink'), ('red', 'Red'), ('purple', 'Purple'), ('brown', 'Brown'), ('green', 'Green'), ('cyan', 'Cyan'), ('lime', 'Lime')], default='wht', max_length=20)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=60)),
                ('location', models.CharField(default='N/A', max_length=20)),
                ('once', models.BooleanField(default=False)),
                ('monday', models.BooleanField(default=False)),
                ('tuesday', models.BooleanField(default=False)),
                ('wednesday', models.BooleanField(default=False)),
                ('thursday', models.BooleanField(default=False)),
                ('friday', models.BooleanField(default=False)),
                ('saturday', models.BooleanField(default=False)),
                ('sunday', models.BooleanField(default=False)),
                ('biweekly', models.BooleanField(default=False)),
                ('duethiswk', models.BooleanField(default=False)),
                ('monthly', models.BooleanField(default=False)),
                ('quarterly', models.BooleanField(default=False)),
                ('complete', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('last_completed', models.DateTimeField(auto_now_add=True)),
                ('assignee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.player')),
            ],
        ),
    ]
